<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


if ( ! class_exists( 'WPPL_Script' ) ) {
	/**
	 * Class WPPL_Script
	 *
	 * Object for script enqueuing.
	 */
	class WPPL_Script implements WPPL_Object {
		public string $handle;

		public string $src;

		public array $deps;

		public $ver;

		public bool $in_footer;

		public function __construct( $handle, $src, $deps = [], $ver = false, $in_footer = false ) {
			$this->handle    = $handle;
			$this->src       = $src;
			$this->deps      = $deps;
			$this->ver       = $ver;
			$this->in_footer = $in_footer;
		}

		public function register() {
			if ( $this->handle && $this->src ) {
				wp_register_script( $this->handle, $this->src, $this->deps, $this->ver, $this->in_footer );
			}
		}

		public function unregister() {
			if ( $this->handle && $this->src ) {
				wp_deregister_script( $this->handle );
			}
		}

		/**
		 * Crate script object for webpacked file, generated by wp-script.
		 *
		 * @param string $handle    Script handle.
		 * @param string $path      Script's file path.
		 * @param string $src       Script's URL.
		 * @param bool   $in_footer Header or footer.
		 *
		 * @return WPPL_Script
		 */
		public static function wp_script(
			string $handle,
			string $path,
			string $src,
			bool $in_footer = false
		): WPPL_Script {
			$asset_file = substr( $path, 0, - 3 ) . '.asset.php';
			$deps       = [];
			$ver        = false;

			if ( file_exists( $asset_file ) && is_readable( $asset_file ) ) {
				/**
				 * @noinspection PhpIncludeInspection
				 * @var          array $asset_file
				 */
				$asset = include $asset_file;
				$deps  = $asset['dependencies'] ?? [];
				$ver   = $asset['version'] ?? false;
			} else {
				$handle = false;
				$src    = false;
			}

			return new WPPL_Script( $handle, $src, $deps, $ver, $in_footer );
		}
	}
}
